### ISSUE TITLE
Add another possibility of completing the http challenge

### ISSUE THREAD

**Issue by 1c3t3a** [kariustobias/acme-rs#20]
Currently we're opening a webserver ourselves, but if the server is currently running an instance of apache or nginx, we need to create a file relative to the Webserver root  (usually `/var/www/..`) and write the token into it (this involves parsing another parameter. If mentoring is wanted, just ask.

**Comment by gsquire** [comment]
I can try and tackle this.

Regarding the web server root, is this something you envisioned having a command line option for? Or were you thinking of having the application discover this by inspecting processes and their configuration files?

**Comment by kariustobias** [comment]
Hello @gsquire, thank you for contributing!

We were thinking, that this option for writing in the `/var/www/html` directory should be the default way, because most of the times it is crucial for the administrator not having to shut down his webserver.
However, if no webserver is running, it would be great if the user receives an error message with the recommendation to use something like a `--standalone` option.

The `--standalone` option would be the current implementation of acme-rs that doesn't require a web server.
If however a webserver is in the current process, then the user should receive a warning, that a web server is currently running. You should be able to determine if a webserver is running just by looking at the open port `80`.

I think the idea of inspecting processes and configuration files for automating this process is a really good idea though! But I am not sure, if it would be worth the extra time needing to be invested... But feel free to come up with a solution for it!

I hope I was able to answer your question. Best regards!

**Comment by gsquire** [comment]
Thanks for the update. I'll start working on this soon!
